Add onnx opset to groqflow config
groq/groqflow pull request #16
Opened 2023-06-06 22:14 UTC by settle

Resolves a compile-time error when using mlagility's benchit.

2023-06-06 22:15 UTC, settle commented
I have read the CLA Document and I hereby sign the CLA

2023-06-07 17:43 UTC, jeremyfowers commented
Please set the groqflow version number to 3.1.0.

2023-06-07 17:44 UTC, jeremyfowers requested changes
Please set the groqflow version number to 3.1.0. Other than that, the PR is good!

2023-06-07 19:09 UTC, jeremyfowers approved these changes

2023-06-07 19:09 UTC, merged